[phases.setup]
nixPkgs = ["php83", "php83Extensions.gd", "nodejs_22"]

[phases.build]
cmds = [
  "php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\"",
  "php composer-setup.php --install-dir=/usr/local/bin --filename=composer",
  "composer install --no-dev --optimize-autoloader",
  "npm install",
  "npm run build"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"